### ISSUE TITLE
Uncaught Promise when trying to follow the same address

### ISSUE THREAD

**Issue by Qoyyuum** [cyberconnecthq/cyberconnect-starter#9]
Hey thanks for creating the starter. Just tried it and already got an error.

![image](https://user-images.githubusercontent.com/971309/151184845-e0554719-d88b-487c-a621-665a2ffbe02f.png)

Steps to reproduce:
1. Connect Wallet Address
2. Enter your same wallet address
3. Click Follow

Expectation: 🤷‍♂️🤷‍♀️ or at least return an error stating unable to follow your own address

Reality: Uncaught Promise.

**Comment by jiayi1992** [comment]
Thank you @Qoyyuum ! Fixed it.
